### PR TITLE
feat(extensions): extensions enable/disable

### PR DESCRIPTION
**Pull request by pavlzk**
### What this PR does 📖
- allows enable/disable extensions and save their status in persisted state

### Which issue(s) this PR fixes 🔨
- Resolve #

### CODE REVIEW

**Review by InfamousVague — APPROVED** [review]

**Comment by phillsatellite** [comment]
Just one small question, the state of toggle will not change after navigating away from Settings 👍  but typing indicator behavior is the same with toggle on or off. Tried new accounts and cargo update/clean 

https://user-images.githubusercontent.com/93608357/206759865-1de716ae-1762-4a1a-ad6e-afc5305c8e5c.mov

**Review by dariusc93 — APPROVED** [review]

**Comment by dariusc93** [comment]
> Just one small question, the state of toggle will not change after navigating away from Settings +1 but typing indicator behavior is the same with toggle on or off. Tried new accounts and cargo update/clean

Thats because the the indicator is enabled by default while this PR makes it so you can enable and disable the extension. In this case, when you enable the extension a button pops up on the right hand side of the text area that allows you to enable or disable the typing indicator.

**Comment by dariusc93** [comment]
I will make a quick comment (since I forgot to do it when approving the PR) that we should probably default back to the default setting of say the indicator rather than for it to stick, but i assume that it would probably have its own configuration in the future that it would rely on.

**Comment by phillsatellite** [comment]
Thanks for clarifying Darius!

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
