### PR TITLE
chore(chat): timer

### PR DESCRIPTION
**Pull request by molimauro**
### What this PR does 📖
- Add call timer on Media container

### Which issue(s) this PR fixes 🔨
- Resolve #

### CODE REVIEW

**Comment by InfamousVague** [comment]
Looks good but can we add it to the settings under the right page on a toggle switch? There should be some copy paste code avail from searching `config.developer` (So people who may want a simpler UI, or on platforms with less real-estate, we can turn it off)

**Comment by molimauro** [comment]
Sure, ill put this under "Audio Video" in the settings page

**Comment by molimauro** [comment]
Done!

**Comment by phillsatellite** [comment]
Hi Mauro! I'm not sure if this is just an error on my side or not but whenever I try to switch over to this branch I get hit with this 

Screenshot 2022-11-25 at 3 14 27 PM

**Review by InfamousVague — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-11-25, às 22 43 46


can't compile this branch

macOS

**Review by InfamousVague — APPROVED** [review]

**Pull request merged**
