### PR TITLE
Feat/multiline support

### PR DESCRIPTION
**Pull request by sdwoodbury**
### What this PR does 📖
- this PR shares code between `components::compose::write` and `components::compose::msg`. the latter did not resize on text input. now it does.  
- a TextArea and IconTextArea were created to do this. The chat reply modal uses IconTextArea, which composes TextArea with an emoji button. 
- the text within the TextArea is "lifted" out so that it can be updated on a button press. 

### Which issue(s) this PR fixes 🔨
- #40
- #101

### CODE REVIEW

**Comment by sdwoodbury** [comment]
don't merge this before  this PR: "redo merge between fix/performance and 121-2 #131"
Update: ready to go.

**Comment by phillsatellite** [comment]
Hi Stewart! I found a few things when testing I wanted to bring to your attention

When user sends a blank message and clicks the Send button it seems the send button will shrink 


https://user-images.githubusercontent.com/93608357/197634142-863cf3ea-316f-4e47-b495-0d5b91610939.mov

I also found when user tries to send a message with multiple lines it will still just send the message as all one line 

https://user-images.githubusercontent.com/93608357/197634250-716030a2-9e95-4cc5-bd19-ce3ec92be91c.mov

Message I was trying to send 

"example 
example 
example "

Sent as "example example example"

**Comment by InfamousVague** [comment]
Cool to add a new bug for the multi-line messages not working as I think that was an issue before

**Comment by dariusc93** [comment]
> Hi Stewart! I found a few things when testing I wanted to bring to your attention
> 
> When user sends a blank message and clicks the Send button it seems the send button will shrink
> Screen.Recording.2022-10-24.at.3.00.46.PM.mov
> 
> I also found when user tries to send a message with multiple lines it will still just send the message as all one line
> Screen.Recording.2022-10-24.at.3.05.45.PM.mov
> 
> Message I was trying to send
> 
> "example example example "
> 
> Sent as "example example example"

Was avoiding doing it, but I went on and added something to CSS for this though i think the preferable solution is to do something without it. 

cc: @phillsatellite @sdwoodbury

**Comment by phillsatellite** [comment]
Screen Shot 2022-10-25 at 6 29 02 PM

After @dariusc93 changes multi line is now fixed and appears correctly 🎉  Was still able to replicate minimizing the send button in chat

**Comment by sdwoodbury** [comment]
I can prevent send when either nothing or just whitespace was entered.
when testing that, I found an issue with the textarea not resizing until the user enters more input

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
