### PR TITLE
feat(topbar): fav button

### LINKED ISSUE #202: Favorites button inside chat
The heart button at the top of a chat should toggle favoriting of a user. The heart should be blue on our secondary background type when the user is hearted, it should be the white outline when the user is not favorited.

### PR DESCRIPTION
**Pull request by molimauro**
### What this PR does 📖
- Title
- Adjust `test/physical/launch_physical_test.sh` and take into account Gum not installed

### Which issue(s) this PR fixes 🔨
- Resolve #202 

### Additional comments 🎤
We need a `.prettierrc`

### CODE REVIEW

**Review by sdwoodbury — APPROVED** [review]
looks good 
Screenshot from 2022-11-14 11-18-52

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
> We need a .prettierrc


seems this one https://github.com/rust-lang/rustfmt is the prettier for rust, thoughts? 🔨

**Comment by sdwoodbury** [comment]
> > We need a .prettierrc
> 
> seems this one https://github.com/rust-lang/rustfmt is the prettier for rust, thoughts? hammer

`.vscode/settings.json` has the following: 
```
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "[rust]": {
    "editor.defaultFormatter": "rust-lang.rust-analyzer"
  }
}
```

**Comment by stavares843** [comment]
maybe isn't working then based on what mauro mentioned above 😂

**Comment by molimauro** [comment]
That is good for Rust files, but it does not cover `.css` files so, based on each dev vscode config, we will have different indentations etc

**Pull request merged**
