### PR TITLE
fix(Compose): fixes #68

### LINKED ISSUE #68: Compose - After sending a message by clicking the send button, chat input is not cleared out
1. Start chat
2. Write a chat message and click on the send button
3. Message is sent but text input is not cleared out

* User will send the same message if only clicks again on send button
* This issue does not happen if user sends the message by pressing "Enter"

### PR DESCRIPTION
**Pull request by InfamousVague**
### What this PR does 📖
- 

### Which issue(s) this PR fixes 🔨
- Resolve #

### CODE REVIEW

**Comment by phillsatellite** [comment]
@stavares843 Wanna try to add me to test this?

**Comment by stavares843** [comment]
whats your ID @phillsatellite

**Comment by phillsatellite** [comment]
`did:key:z6Mkky6efZqBtteUodhkgJv6u9wEmwWhmFTLB8mYhABanVpp`

@stavares843

**Comment by stavares843** [comment]
mine is
```
did:key:z6MkvPh2usSyp6jL5i4hecxHTNnRwK4FGyyzb8EYMh2Rhi9X
````
gonna add you

**Comment by stavares843** [comment]
added 🔨

**Comment by phillsatellite** [comment]
> did:key:z6MkvPh2usSyp6jL5i4hecxHTNnRwK4FGyyzb8EYMh2Rhi9X

accepted and sent messages 🎉

**Comment by stavares843** [comment]
Captura de ecrã 2022-10-02, às 00 04 59

still shows as pending for me, no message received 💥

**Comment by stavares843** [comment]
updated now 😂

**Review by stavares843 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
