### PR TITLE
chore(responsive): make sidebar on chat view responsive

### LINKED ISSUE #282: Make Desktop app Responsive
Similar to how telegram collapses down as you change the window size.

Auto collapse to sidebar, hide main content window, and when user navigates, hide sidebar and show content window full screen. Make a way to go back to sidebar

This will require re-working some of the windows, so to keep pr's small and manageable, i will make tickets to implement this on all the main views

### PR DESCRIPTION
**Pull request by WanderingHogan**
### What this PR does 📖
This makes the chat window responsive at 600px, and adds something to the global state to indicate if we want to show or hide the side bar (so it can be used soon in all the different places a user might need it).

Currently only implemented in the chat window as the structure of some of the other things, like files and chat, need to be modified to make them responsive

### Which issue(s) this PR fixes 🔨
- Resolve #282

### Special notes for reviewers 🗒️
- I need to make things in the chat window responsive during resize, and then implement this in the other screens.
- I looked at the CPU usage and it doesn't appear this is affecting things any more than the base dev branch, but i may be wrong

https://user-images.githubusercontent.com/2993032/201487833-f1e1a87c-fa2c-46f7-b80d-427ffc11983c.mov

### Additional comments 🎤
I went in and fixed the things the github action for `Continuous integration / Rustfmt (pull_request)` was complaining about

### CODE REVIEW

**Comment by InfamousVague** [comment]
My only change would be to make it so the chat screen fills available space better at smaller sizes like here, basically just removing the extra padding around the sides.
image

into

image

**Comment by WanderingHogan** [comment]
@InfamousVague updated

https://user-images.githubusercontent.com/2993032/201683593-aab87536-d0d2-4a3d-9001-7085f7b5a0bb.mov

**Comment by sdwoodbury** [comment]
https://user-images.githubusercontent.com/8636602/201706375-281669c4-8f94-4619-88db-c4af0dc0ce8c.mp4

the blur behind message replies goes away when the window gets too small

**Review by sdwoodbury — CHANGES_REQUESTED** [review]
maintain blur while replying to a message

**Comment by InfamousVague** [comment]
> maintain blur while replying to a message

Let's open a new PR for this, this is actually also an issue on dev I'll patch it up today.

**Pull request merged**
