### PR TITLE
fix(context): improve context menu styles, add global svg rules for e…

### LINKED ISSUE #402: improve context menu style/ux
- hr with margin creates a ton of un-clickable space
- contrast is pretty low, hard to tell where the edge is
- box shadow
- red item hover should turn background red & text white

### PR DESCRIPTION
**Pull request by josephmcg**
…ase of use

### What this PR does 📖
- improve context menu styles
- switch svg stroke to currentColor by default. This will save us from a lot of extra stroke color rules

### Which issue(s) this PR fixes 🔨
- Resolve #402 

### Special notes for reviewers 🗒️
- it would be good to create empty space on the left if no icon is provided. the text would look better if it was always aligned. not sure how to implement this

### CODE REVIEW

**Review by InfamousVague — APPROVED** [review]
lgtm

**Comment by molimauro** [comment]
I noticed this error on my branch that also happens here:

image

It happens when going from the chat to another page and then back to the chat. It seems related to the contextmenu, not sure if here is the right place to fix.

PS: we should check that every time we include the `context.js` script we're not adding a new `contextmenu` event listener and not removing the old one

**Review by phillsatellite — APPROVED** [review]

**Comment by phillsatellite** [comment]
I put the question label for Mauro's comment above

**Comment by josephmcg** [comment]
that would be good to fix separately

**Pull request merged**
